"""Increase task title & description fields length

Revision ID: 3f094bb57e67
Revises: 010d44f94874
Create Date: 2023-12-25 23:31:21.243350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f094bb57e67'
down_revision: Union[str, None] = '010d44f94874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('task', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
